### ISSUE TITLE
Error with opening scenes in Tiled

### ISSUE THREAD

**Issue by logwet** [logwet/Unity-2D-RPG#2]
For some reason I can't open neither the 1st forest scene or the house scene in Tiled.
In the 1st forest scene it comes up with an error message saying that the Barrel tiles are inaccessible.
The house scene comes up with a error message that the tile sheet the carpet comes from is inaccessible.
However, when I inspect the project files, none of the assets are corrupted or gone.
Please reply if you know what the issue at hand is.

**Comment by Devnithz** [comment]
Skype me.

*--------------------------------*
*Regards,*
*Devnith De Silva*
Email: Des0021@mwsc.vic.edu.au
Website : http://devnith.bitballoon.com/


On 6 Jul 2015, at 9:33 pm, Sachila Herath <notifications@github.com> wrote:

For some reason I can't open neither the 1st forest scene or the house
scene in Tiled.
In the 1st forest scene it comes up with an error message saying that the
Barrel tiles are inaccessible.
The house scene comes up with a error message that the tile sheet the
carpet comes from is inaccessible.
However, when I inspect the project files, none of the assets are corrupted
or gone.
Please reply if you know what the issue at hand is.

—
Reply to this email directly or view it on GitHub
<https://github.com/logwet/Unity-2D-RPG/issues/2>.
